//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAIMIStock.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Suministros
    {
        public int idSuministro { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de código es obligatorio")]
        public string codigo { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de nombre es obligatorio")]
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> objetoGasto { get; set; }
        public string localizacion { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de cantidad es obligatorio")]
        public int cantidad { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de límite mínimo de cantidad es obligatorio")]
        public int limiteSuministro { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de categoría es obligatorio")]
        public int idCategoria { get; set; }
    
        public virtual CategoriasSuministros CategoriasSuministros { get; set; }

        [NotMapped]
        public int selectedSupply { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem> supplies { get; set; }
    }
}
