//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAIMIStock.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de usuario es obligatorio")]
        [StringLength(50)]
        public string nombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de contraseña es obligatorio")]
        [StringLength(50)]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<bool> isAdmin { get; set; }

        [NotMapped]
        public string LoginErrorMessage { get; set; }

        [NotMapped]
        public string UpdatePasswordErrorMessage { get; set; }
        public virtual Roles Roles { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "El campo de nueva contraseña es obligatorio")]
        [DataType(DataType.Password)]
        public string newPassword { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "El campo de confirmación de contraseña es obligatorio")]
        [Compare("newPassword", ErrorMessage = "Las contraseñas no coinciden")]
        [DataType(DataType.Password)]
        public string confirmPassword { get; set; }
    }
}
