//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LAIMIStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [Key]
        public int idUsuario { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Este campo es obligatorio")]
        [StringLength(50)]
        public string nombre { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Este campo es obligatorio")]
        [StringLength(50)]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    
        public virtual Roles Roles { get; set; }

        [NotMapped]
        public string LoginErrorMessage { get; set; }
    }
}
